services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CACHEBUST=${CACHEBUST:-1}
    container_name: hemotec_app
    restart: always
    ports:
      - "127.0.0.1:8001:8000"
    environment:
      - PYTHONUNBUFFERED=1