from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from starlette.middleware.sessions import SessionMiddleware
import uvicorn

from data.repo import cidade_repo
from data.repo import campanha_repo
from data.repo import usuario_repo
from data.repo import gestor_repo
from data.repo import instituicao_repo
from data.repo import assinatura_repo
from data.repo import plano_repo
from data.repo import licenca_repo
from data.repo import adm_unidade_repo
from data.repo import adm_campanha_repo
from data.repo import unidade_coleta_repo
from data.repo import estoque_repo
from data.repo import notificacao_repo
from data.repo import colaborador_repo
from data.repo import agendamento_repo
from data.repo import doador_repo
from data.repo import doacao_repo
from data.repo import exame_repo
from data.repo import prontuario_repo

# Importando os routers públicos
from routes.publico.api_public import router as public_router
from routes.publico.login import router as login_router
from routes.publico.login_cadastro import router as cadastro_router
from routes.publico.login_esqueceu_senha import router as login_esqueceu_senha_router
from routes.publico.sobre import router as sobre_router
from routes.publico.campanha import router as campanha_router
from routes.publico.contato import router as contato_router

# Importando os routers do doador
from routes.doador_temporário.doador import router as doador_router
from routes.doador_temporário.doador_campanhas import router as doador_campanha_router
from routes.doador_temporário.doador_agendamentos import router as doador_agendamento_router
from routes.doador.doador_agendamento_confirmar import router as doador_agendamento_confirmar_router
from routes.doador.doador_agendamento_historico_agendamentos import router as doador_agendamento_historico_router
from routes.doador_temporário.doador_notificacoes import router as doador_notificacao_router
from routes.doador.doador_meu_perfil import router as doador_meu_perfil_router
from routes.doador_temporário.doador_configuracoes import router as doador_configuracoes_router
from routes.doador.doador_novo_doador import router as doador_novo_doador_router
from routes.doador.doador_reagendamento import router as doador_reagendamento_router
from routes.doador.doador_sair import router as doador_sair_router
from routes.doador.doador_estoque import router as doador_estoque_router
from routes.doador_temporário.doador_carteira import router as doador_carteira_router

# Importando os routers do colaborador
from routes.colaborador.colaborador import router as colaborador_router
from routes.colaborador.colaborador_campanha import router as colaborador_campanha_router
from routes.colaborador.colaborador_campanha_adicionar import router as colaborador_campanha_adicionar_router
from routes.colaborador.colaborador_campanha_alterar import router as colaborador_campanha_alterar_router
from routes.colaborador.colaborador_campanha_excluir import router as colaborador_campanha_excluir_router
from routes.colaborador.colaborador_campanha_detalhe import router as colaborador_campanha_detalhe_router
from routes.colaborador.colaborador_notificacao import router as colaborador_notificacao_router
from routes.colaborador.colaborador_agendamento import router as colaborador_agendamento_router
from routes.colaborador.colaborador_agendamento_adicionar import router as colaborador_agendamento_adicionar_router
from routes.colaborador.colaborador_agendamento_alterar import router as colaborador_agendamento_alterar_router
from routes.colaborador.colaborador_agendamento_excluir import router as colaborador_agendamento_excluir_router
from routes.colaborador.colaborador_doacao import router as colaborador_doacao_router
from routes.colaborador.colaborador_doacao_adicionar import router as colaborador_doacao_adicionar_router
from routes.colaborador.colaborador_doacao_alterar import router as colaborador_doacao_alterar_router
from routes.colaborador.colaborador_doacao_excluir import router as colaborador_doacao_excluir_router
from routes.colaborador.colaborador_doacao_detalhe import router as colaborador_doacao_detalhe_router
from routes.colaborador.colaborador_doacao_anexar_resultado import router as colaborador_doacao_anexar_resultado_router
from routes.colaborador.colaborador_disponibilidade_coleta import router as colaborador_disponibilidade_coleta_router

# Importando os routers do administrador de unidade de coleta
from routes.adm_unidade.administrador import router as administrador_router
from routes.adm_unidade.administrador_relatorios import router as administrador_relatorios_router
from routes.adm_unidade.administrador_relatorios_por_tipo_sanguineo import router as administrador_relatorios_por_tipo_sanguineo_router
from routes.adm_unidade.administrador_relatorios_por_periodo import router as administrador_relatorios_por_periodo_router
from routes.adm_unidade.administrador_notificacao import router as administrador_notificacao_router
from routes.adm_unidade.administrador_colaboradores import router as administrador_colaboradores_router
from routes.adm_unidade.administrador_colaboradores_excluir import router as administrador_colaboradores_excluir_router
from routes.adm_unidade.administrador_colaboradores_detalhes import router as administrador_colaboradores_detalhes_router
from routes.adm_unidade.administrador_colaboradores_alterar import router as administrador_colaboradores_alterar_router
from routes.adm_unidade.administrador_colaboradores_adicionar import router as administrador_colaboradores_adicionar_router
from routes.adm_unidade.administrador_campanha import router as administrador_campanha_router
from routes.adm_unidade.administrador_campanha_excluir import router as administrador_campanha_excluir_router
from routes.adm_unidade.administrador_campanha_detalhes import router as administrador_campanha_detalhes_router
from routes.adm_unidade.administrador_campanha_alterar import router as administrador_campanha_alterar_router
from routes.adm_unidade.administrador_campanha_adicionar import router as administrador_campanha_adicionar_router

# Importando os routers do gestor
from routes.gestor.gestor import router as gestor_router
from routes.gestor.gestor_relatorio import router as gestor_relatorio_router
from routes.gestor.gestor_relatorio_colaborador import router as gestor_relatorio_colaborador_router
from routes.gestor.gestor_relatorio_doador import router as gestor_relatorio_doador_router
from routes.gestor.gestor_administrador import router as gestor_administrador_router
from routes.gestor.gestor_administrador_adicionar import router as gestor_administrador_adicionar_router
from routes.gestor.gestor_administrador_alterar import router as gestor_administrador_alterar_router
from routes.gestor.gestor_administrador_detalhe import router as gestor_administrador_detalhe_router
from routes.gestor.gestor_administrador_excluir import router as gestor_administrador_excluir_router
from routes.gestor.gestor_centro_coleta import router as gestor_centro_coleta_router
from routes.gestor.gestor_centro_coleta_adicionar import router as gestor_centro_coleta_adicionar_router
from routes.gestor.gestor_centro_coleta_alterar import router as gestor_centro_coleta_alterar_router
from routes.gestor.gestor_centro_coleta_excluir import router as gestor_centro_coleta_excluir_router
from routes.gestor.gestor_centro_coleta_detalhe import router as gestor_centro_coleta_detalhe_router

# Importando os routers do usuario
from routes.usuario.usuario_alterar_senha import router as usuario_alterar_senha_router
from routes.usuario.usuario_sair import router as usuario_sair_router

app = FastAPI()
app.add_middleware(SessionMiddleware, secret_key="your-secret-key-here")
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

cidade_repo.criar_tabela()
usuario_repo.criar_tabela()
campanha_repo.criar_tabela()
plano_repo.criar_tabela()
instituicao_repo.criar_tabela()
gestor_repo.criar_tabela()
assinatura_repo.criar_tabela()
licenca_repo.criar_tabela()
unidade_coleta_repo.criar_tabela()
estoque_repo.criar_tabela()
adm_unidade_repo.criar_tabela()
adm_campanha_repo.criar_tabela()
notificacao_repo.criar_tabela()
colaborador_repo.criar_tabela()
doador_repo.criar_tabela()
agendamento_repo.criar_tabela()
doacao_repo.criar_tabela()
exame_repo.criar_tabela()
prontuario_repo.criar_tabela()

#routers públicos
app.include_router(public_router)
app.include_router(login_router)
app.include_router(cadastro_router)
app.include_router(login_esqueceu_senha_router)
app.include_router(sobre_router)
app.include_router(campanha_router)
app.include_router(contato_router)

#routers do doador
app.include_router(doador_router)
app.include_router(doador_campanha_router)
app.include_router(doador_agendamento_router)
app.include_router(doador_agendamento_confirmar_router)
app.include_router(doador_agendamento_historico_router)
app.include_router(doador_notificacao_router)
app.include_router(doador_meu_perfil_router)
app.include_router(doador_configuracoes_router)
app.include_router(doador_novo_doador_router)
app.include_router(doador_reagendamento_router)
app.include_router(doador_sair_router)
app.include_router(doador_estoque_router)
app.include_router(doador_carteira_router)


#routers do colaborador
app.include_router(colaborador_router)
app.include_router(colaborador_campanha_router)
app.include_router(colaborador_campanha_adicionar_router)
app.include_router(colaborador_campanha_alterar_router)
app.include_router(colaborador_campanha_excluir_router)
app.include_router(colaborador_campanha_detalhe_router)
app.include_router(colaborador_notificacao_router)
app.include_router(colaborador_agendamento_router)
app.include_router(colaborador_agendamento_adicionar_router)
app.include_router(colaborador_agendamento_alterar_router)
app.include_router(colaborador_agendamento_excluir_router)
app.include_router(colaborador_doacao_router)
app.include_router(colaborador_doacao_adicionar_router)
app.include_router(colaborador_doacao_alterar_router)
app.include_router(colaborador_doacao_excluir_router)
app.include_router(colaborador_doacao_detalhe_router)
app.include_router(colaborador_doacao_anexar_resultado_router)
app.include_router(colaborador_disponibilidade_coleta_router)

#routers do adm_unidade
app.include_router(administrador_router)
app.include_router(administrador_relatorios_router)
app.include_router(administrador_relatorios_por_tipo_sanguineo_router)
app.include_router(administrador_relatorios_por_periodo_router)
app.include_router(administrador_notificacao_router)
app.include_router(administrador_colaboradores_router)
app.include_router(administrador_colaboradores_excluir_router)
app.include_router(administrador_colaboradores_detalhes_router)
app.include_router(administrador_colaboradores_alterar_router)
app.include_router(administrador_colaboradores_adicionar_router)
app.include_router(administrador_campanha_router)
app.include_router(administrador_campanha_excluir_router)
app.include_router(administrador_campanha_detalhes_router)
app.include_router(administrador_campanha_alterar_router)
app.include_router(administrador_campanha_adicionar_router)

#routers do gestor
app.include_router(gestor_router)
app.include_router(gestor_relatorio_router)
app.include_router(gestor_relatorio_colaborador_router)
app.include_router(gestor_relatorio_doador_router)
app.include_router(gestor_administrador_router)
app.include_router(gestor_administrador_adicionar_router)
app.include_router(gestor_administrador_alterar_router)
app.include_router(gestor_administrador_detalhe_router)
app.include_router(gestor_administrador_excluir_router)
app.include_router(gestor_centro_coleta_router)
app.include_router(gestor_centro_coleta_adicionar_router)
app.include_router(gestor_centro_coleta_alterar_router)
app.include_router(gestor_centro_coleta_excluir_router)
app.include_router(gestor_centro_coleta_detalhe_router)

#routers do usuario
app.include_router(usuario_alterar_senha_router)
app.include_router(usuario_sair_router)


if __name__ == "__main__":
    uvicorn.run(app="main:app", host="127.0.0.1", port=8000, reload=True)