from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from starlette.middleware.sessions import SessionMiddleware
import secrets
import uvicorn

app = FastAPI()

# Gerar chave secreta (em produção, use variável de ambiente!)
# Chave fixa para manter sessões após reload do servidor
SECRET_KEY = "hemotec_development_secret_key_12345678901234567890123456789012"

# Adicionar middleware de sessão
app.add_middleware(
    SessionMiddleware, 
    secret_key=SECRET_KEY,
    max_age=28800,  # Sessão expira em 8 horas (28800 segundos)
    same_site="lax",
    https_only=False  # Em produção, mude para True com HTTPS
)

app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

# Importando os repositórios
from data.repo import cidade_repo
from data.repo import campanha_repo
from data.repo import usuario_repo
from data.repo import gestor_repo
from data.repo import possivel_gestor_repo
from data.repo import instituicao_repo
from data.repo import assinatura_repo
from data.repo import plano_repo
from data.repo import licenca_repo
from data.repo import adm_unidade_repo
from data.repo import adm_campanha_repo
from data.repo import unidade_coleta_repo
from data.repo import estoque_repo
from data.repo import notificacao_repo
from data.repo import colaborador_repo
from data.repo import agenda_repo
from data.repo import horario_funcionamento_repo
from data.repo import agendamento_repo
from data.repo import doador_repo
from data.repo import doacao_repo
from data.repo import exame_repo
from data.repo import prontuario_repo

# Importando os routers públicos
from routes.publico.api_public import router as publico_api_public_router
from routes.publico.publico import router as publico_router
from routes.publico.publico_login import router as publico_login_router
from routes.publico.publico_sobre import router as publico_sobre_router
from routes.publico.publico_campanha import router as publico_campanha_router
from routes.publico.publico_contato import router as publico_contato_router
from routes.publico.publico_adquirir_assinatura import router as publico_adquirir_assinatura_router
from routes.publico.publico_cadastrar_possivel_gestor import router as publico_cadastrar_possivel_gestor_router
from routes.publico.publico_visualizar_plano import router as publico_visualizar_plano_router
from routes.publico.publico_finalizar_cadastro import router as publico_finalizar_cadastro_router
from routes.publico.publico_cadastrar import router as publico_cadastrar_doador_router
from routes.publico.publico_validar_telefone import router as publico_validar_telefone_router
from routes.publico.publico_confirmar_cadastro import router as publico_confirmar_cadastro_router
from routes.publico.publico_redefinir_senha import router as publico_redefinir_senha_router
from routes.publico.publico_validar_token import router as publico_validar_token_router
from routes.publico.publico_criar_nova_senha import router as publico_criar_nova_senha_router
from routes.publico.publico_confirmar_redefinicao_senha import router as publico_confirmar_redefinicao_senha_router


# Importando os routers do doador
from routes.doador.doador import router as doador_router
from routes.doador.doador_notificacoes import router as doador_notificacao_router
from routes.doador.doador_doacoes import router as doador_doacoes_router
from routes.doador.doador_doacoes_api import router as doador_doacoes_api_router
from routes.doador.doador_doacoes_detalhes import router as doador_doacoes_detalhes_router
from routes.usuario.dados_cadastrais import router as doador_dados_cadastrais_router
from routes.doador.doador_configuracoes import router as doador_configuracoes_router
from routes.doador.doador_carteira import router as doador_carteira_router
from routes.doador.doador_campanhas import router as doador_campanha_router
from routes.doador.doador_campanhas_detalhes import router as doador_campanha_detalhes_router
from routes.doador.doador_agendamentos import router as doador_agendamento_router
from routes.doador.doador_agendamentos_excluir import router as doador_agendamento_excluir_router
from routes.doador.doador_agendamentos_alterar import router as doador_agendamento_alterar_router
from routes.doador.doador_agendamentos_adicionar import router as doador_agendamento_adicionar_router
from routes.doador.doador_agendamentos_adicionar_confirmacao import router as doador_agendamento_adicionar_confirmacao_router
from routes.doador.doador_agendamento_api import router as doador_agendamento_api_router

# Importando os routers de API
from routes.api.api_agenda import router as api_agenda_router

# Importando os routers do colaborador
from routes.colaborador.colaborador import router as colaborador_router
from routes.colaborador.colaborador_campanha import router as colaborador_campanha_router
from routes.colaborador.colaborador_campanha_adicionar import router as colaborador_campanha_adicionar_router
from routes.colaborador.colaborador_campanha_alterar import router as colaborador_campanha_alterar_router
from routes.colaborador.colaborador_campanha_excluir import router as colaborador_campanha_excluir_router
from routes.colaborador.colaborador_campanha_detalhe import router as colaborador_campanha_detalhe_router
from routes.colaborador.colaborador_notificacao import router as colaborador_notificacao_router
from routes.colaborador.colaborador_agendamento import router as colaborador_agendamento_router
from routes.colaborador.colaborador_agendamento_adicionar import router as colaborador_agendamento_adicionar_router
from routes.colaborador.colaborador_agendamento_adicionar_confirmacao import router as colaborador_agendamento_adicionar_confirmacao_router
from routes.colaborador.colaborador_agendamento_alterar import router as colaborador_agendamento_alterar_router
from routes.colaborador.colaborador_agendamento_excluir import router as colaborador_agendamento_excluir_router
from routes.colaborador.debug_agendamento import router as debug_agendamento_router
from routes.colaborador.colaborador_doacao import router as colaborador_doacao_router
from routes.colaborador.colaborador_doacao_adicionar import router as colaborador_doacao_adicionar_router
from routes.colaborador.colaborador_doacao_alterar import router as colaborador_doacao_alterar_router
from routes.colaborador.colaborador_doacao_excluir import router as colaborador_doacao_excluir_router
from routes.colaborador.colaborador_doacao_detalhe import router as colaborador_doacao_detalhe_router
from routes.colaborador.colaborador_doacao_triagem import router as colaborador_doacao_triagem_router
from routes.colaborador.colaborador_doacao_anexar_resultado import router as colaborador_doacao_anexar_resultado_router
from routes.colaborador.colaborador_disponibilidade_coleta import router as colaborador_disponibilidade_coleta_router
from routes.colaborador.colaborador_meu_perfil import router as colaborador_meu_perfil_router

# Importando os routers do administrador de unidade de coleta
from routes.adm_unidade.administrador import router as administrador_router
from routes.adm_unidade.administrador_relatorios import router as administrador_relatorios_router
from routes.adm_unidade.administrador_relatorios_por_tipo_sanguineo import router as administrador_relatorios_por_tipo_sanguineo_router
from routes.adm_unidade.administrador_relatorios_por_periodo import router as administrador_relatorios_por_periodo_router
from routes.adm_unidade.administrador_notificacao import router as administrador_notificacao_router
from routes.adm_unidade.administrador_colaboradores import router as administrador_colaboradores_router
from routes.adm_unidade.administrador_colaboradores_excluir import router as administrador_colaboradores_excluir_router
from routes.adm_unidade.administrador_colaboradores_detalhes import router as administrador_colaboradores_detalhes_router
from routes.adm_unidade.administrador_colaboradores_alterar import router as administrador_colaboradores_alterar_router
from routes.adm_unidade.administrador_colaboradores_adicionar import router as administrador_colaboradores_adicionar_router
from routes.adm_unidade.administrador_campanha import router as administrador_campanha_router
from routes.adm_unidade.administrador_campanha_excluir import router as administrador_campanha_excluir_router
from routes.adm_unidade.administrador_campanha_detalhes import router as administrador_campanha_detalhes_router
from routes.adm_unidade.administrador_campanha_alterar import router as administrador_campanha_alterar_router
from routes.adm_unidade.administrador_campanha_adicionar import router as administrador_campanha_adicionar_router

# Importando os routers do gestor
from routes.gestor.gestor import router as gestor_router
from routes.gestor.gestor_relatorio import router as gestor_relatorio_router
from routes.gestor.gestor_relatorio_colaborador import router as gestor_relatorio_colaborador_router
from routes.gestor.gestor_relatorio_doador import router as gestor_relatorio_doador_router
from routes.gestor.gestor_administrador import router as gestor_administrador_router
from routes.gestor.gestor_administrador_adicionar import router as gestor_administrador_adicionar_router
from routes.gestor.gestor_administrador_alterar import router as gestor_administrador_alterar_router
from routes.gestor.gestor_administrador_detalhe import router as gestor_administrador_detalhe_router
from routes.gestor.gestor_administrador_excluir import router as gestor_administrador_excluir_router
from routes.gestor.gestor_centro_coleta import router as gestor_centro_coleta_router
from routes.gestor.gestor_centro_coleta_adicionar import router as gestor_centro_coleta_adicionar_router
from routes.gestor.gestor_centro_coleta_alterar import router as gestor_centro_coleta_alterar_router
from routes.gestor.gestor_centro_coleta_excluir import router as gestor_centro_coleta_excluir_router
from routes.gestor.gestor_centro_coleta_detalhe import router as gestor_centro_coleta_detalhe_router

# Importando os routers do usuario
from routes.usuario.usuario_alterar_senha import router as usuario_alterar_senha_router
from routes.usuario.usuario_sair import router as usuario_sair_router

#Importando os routers de telas de teste
from routes.rotas_teste.doador_agendamento_historico_agendamentos import router as doador_agendamento_historico_agendamentos_teste_router
from routes.rotas_teste.doador_estoque import router as doador_estoque_teste_router

#Importando routers de atenticação
from routes.auth_routes import router as auth_router

cidade_repo.criar_tabela()
horario_funcionamento_repo.criar_tabela()
usuario_repo.criar_tabela()
campanha_repo.criar_tabela()
plano_repo.criar_tabela()
instituicao_repo.criar_tabela()
gestor_repo.criar_tabela()
possivel_gestor_repo.criar_tabela()
assinatura_repo.criar_tabela()
licenca_repo.criar_tabela()
unidade_coleta_repo.criar_tabela()
estoque_repo.criar_tabela()
adm_unidade_repo.criar_tabela()
adm_campanha_repo.criar_tabela()
notificacao_repo.criar_tabela()
colaborador_repo.criar_tabela()
doador_repo.criar_tabela()
agenda_repo.criar_tabela()
agendamento_repo.criar_tabela()
doacao_repo.criar_tabela()
exame_repo.criar_tabela()
prontuario_repo.criar_tabela()

#routers públicos
app.include_router(publico_api_public_router)
app.include_router(publico_router)
app.include_router(publico_login_router)
app.include_router(publico_sobre_router)
app.include_router(publico_campanha_router)
app.include_router(publico_contato_router)
app.include_router(publico_adquirir_assinatura_router)
app.include_router(publico_cadastrar_possivel_gestor_router)
app.include_router(publico_visualizar_plano_router)
app.include_router(publico_finalizar_cadastro_router)
app.include_router(publico_cadastrar_doador_router)
app.include_router(publico_validar_telefone_router)
app.include_router(publico_confirmar_cadastro_router)
app.include_router(publico_redefinir_senha_router)
app.include_router(publico_validar_token_router)
app.include_router(publico_criar_nova_senha_router)
app.include_router(publico_confirmar_redefinicao_senha_router)

#routers do doador
app.include_router(doador_router)
app.include_router(doador_notificacao_router)
app.include_router(doador_doacoes_router)
app.include_router(doador_doacoes_api_router)
app.include_router(doador_doacoes_detalhes_router)
app.include_router(doador_dados_cadastrais_router)
app.include_router(doador_configuracoes_router)
app.include_router(doador_carteira_router)
app.include_router(doador_campanha_router)
app.include_router(doador_campanha_detalhes_router)
app.include_router(doador_agendamento_router)
app.include_router(doador_agendamento_excluir_router)
app.include_router(doador_agendamento_alterar_router)
app.include_router(doador_agendamento_adicionar_router)
app.include_router(doador_agendamento_adicionar_confirmacao_router)
app.include_router(doador_agendamento_api_router)

#routers de API
app.include_router(api_agenda_router)

#routers do colaborador
app.include_router(colaborador_router)
app.include_router(colaborador_campanha_router)
app.include_router(colaborador_campanha_adicionar_router)
app.include_router(colaborador_campanha_alterar_router)
app.include_router(colaborador_campanha_excluir_router)
app.include_router(colaborador_campanha_detalhe_router)
app.include_router(colaborador_notificacao_router)
app.include_router(debug_agendamento_router)
app.include_router(colaborador_agendamento_router)
app.include_router(colaborador_agendamento_adicionar_router)
app.include_router(colaborador_agendamento_adicionar_confirmacao_router)
app.include_router(colaborador_agendamento_alterar_router)
app.include_router(colaborador_agendamento_excluir_router)
app.include_router(colaborador_doacao_router)
app.include_router(colaborador_doacao_adicionar_router)
app.include_router(colaborador_doacao_alterar_router)
app.include_router(colaborador_doacao_excluir_router)
app.include_router(colaborador_doacao_detalhe_router)
app.include_router(colaborador_doacao_triagem_router)
app.include_router(colaborador_doacao_anexar_resultado_router)
app.include_router(colaborador_disponibilidade_coleta_router)
app.include_router(colaborador_meu_perfil_router)

#routers do adm_unidade
app.include_router(administrador_router)
app.include_router(administrador_relatorios_router)
app.include_router(administrador_relatorios_por_tipo_sanguineo_router)
app.include_router(administrador_relatorios_por_periodo_router)
app.include_router(administrador_notificacao_router)
app.include_router(administrador_colaboradores_router)
app.include_router(administrador_colaboradores_excluir_router)
app.include_router(administrador_colaboradores_detalhes_router)
app.include_router(administrador_colaboradores_alterar_router)
app.include_router(administrador_colaboradores_adicionar_router)
app.include_router(administrador_campanha_router)
app.include_router(administrador_campanha_excluir_router)
app.include_router(administrador_campanha_detalhes_router)
app.include_router(administrador_campanha_alterar_router)
app.include_router(administrador_campanha_adicionar_router)

#routers do gestor
app.include_router(gestor_router)
app.include_router(gestor_relatorio_router)
app.include_router(gestor_relatorio_colaborador_router)
app.include_router(gestor_relatorio_doador_router)
app.include_router(gestor_administrador_router)
app.include_router(gestor_administrador_adicionar_router)
app.include_router(gestor_administrador_alterar_router)
app.include_router(gestor_administrador_detalhe_router)
app.include_router(gestor_administrador_excluir_router)
app.include_router(gestor_centro_coleta_router)
app.include_router(gestor_centro_coleta_adicionar_router)
app.include_router(gestor_centro_coleta_alterar_router)
app.include_router(gestor_centro_coleta_excluir_router)
app.include_router(gestor_centro_coleta_detalhe_router)

#routers do usuario
app.include_router(usuario_alterar_senha_router)
app.include_router(usuario_sair_router)

#routers das telas de testes
app.include_router(doador_agendamento_historico_agendamentos_teste_router)
app.include_router(doador_estoque_teste_router)

#routers de autenticação
app.include_router(auth_router)

if __name__ == "__main__":
    uvicorn.run(app="main:app", host="127.0.0.1", port=8000, reload=True)